Month 12/step 1
daryamakavchik/algososh pull request #9
Opened 2022-11-09 05:03 UTC by daryamakavchik

2022-11-09 07:59 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Работа проделана огромная.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы.

### **Но есть несколько замечаний, которые нужно исправить:**

- Вам нужно создать файл `.gitignore`, а также добавить туда папку `node_modules`.

- По чек-листу во время анимации алгоритмов на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма;

- "Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. Показал на примере fibonacci-page

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

- Последовательность фибоначчи:

  - Если ввести число 5, то результат должен быть равен `1,1,2,3,5,8`, а у вас `0,1,1,2,3,5`.

  - Максимально допустимое число должно быть `19`, а у вас не срабатывает условие.

  - Желательно ограничить ввод отрицательных чисел.

- Очередь:

  - Запретите добавление элемента когда очередь заполнена.

  - https://yadi.sk/d/L_zfk2hWhB8DtA - кнопки включения визуализации алгоритма должны быть активны, только если введены валидные данные и структура данных допускает это действие в данный момент. Обратите внимание на кнопки: `Удалить` и `Очистить`.

- Связный список:

  - https://yadi.sk/d/wuEtDddMNNKrqg - кнопки включения визуализации алгоритма должны быть активны, только если введены валидные данные и структура данных допускает это действие в данный момент.

  - Если добавить несколько по 1 раз в `head` и в `tail`, то возможность добавить новые элементы блокируются.
    https://disk.yandex.ru/i/uF0l_O6lXDF1lg;

  - Когда остаётся последний элемент, запретите удаление, либо продумайте алгоритм, при котором у вас не будут возникать ошибки, и алгоритм продолжит свою нормальную работу. https://disk.yandex.ru/i/KzjDOV3XZGiixg

  - Нужно ограничить добавление и удаление по индексу, если индекс больше длины списка.
    https://yadi.sk/d/zW51DdIZjMtLmw
    

### **Сделает код лучше:**

- Лучше очистить приложение от лишних файлов, которые остались при инициализации create-react-app. (App.test.tsx)

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const getFibonacciNumbers = async (n: string) => {
**Можно лучше:**

По чек-листу: должна быть реализована функция getFibonacciNumbers, которая принимает количество чисел как параметр и возвращает требуемый массив чисел последовательности Фибоначчи; 

Она у вас есть, но только название не то. Стоит изменить название функции.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +            min={1}
**Надо исправить:**

Здесь и во всём проекте.
"Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
>        await delay(500);
**Надо исправить:**

Нужно вынести тайминги в константы.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +}
**Надо исправить:**

классы, описывающие работу структур данных, вынесены в отдельные файлы в папке соответствующего компонента.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    }
**Можно лучше:**

При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```js
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +                index === indexOfInputValue && (
**Можно лучше:** Такие большие условия лучше выносить в отдельную переменную.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +}
**Надо исправить:**

классы, описывающие работу структур данных, вынесены в отдельные файлы в папке соответствующего компонента.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +    }
**Можно лучше:** можно сразу возвращать условие, а не `true/false`.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +}
**Надо исправить:**

классы, описывающие работу структур данных, вынесены в отдельные файлы в папке соответствующего компонента.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +    const arr = countFibonacci(+inputValue);
**Можно лучше:** 

По чек-листу, эта функция должна называться `getFibonacciNumbers`.
Лучше измените название функции на `getFibonacciNumbers`, чтобы не было недопониманий.

2022-11-09 07:59 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +          style={{ maxWidth: "204px" }}
**Надо исправить:**

Здесь и далее. 
Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-11-09 19:41 UTC, daryamakavchik commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const getFibonacciNumbers = async (n: string) => {
странно, кажется displayfib был в main, f в ветке month-12/step-1 уже по-другому 
<img width="777" alt="Screen Shot 2022-11-09 at 11 39 19 AM" src="https://user-images.githubusercontent.com/90967822/200925633-c99174d2-1de8-4960-adc9-265dc5b802ba.png">

2022-11-09 19:45 UTC, daryamakavchik commented on src/components/fibonacci-page/fibonacci-page.tsx
> +  const getFibonacciNumbers = async (n: string) => {
я так и переименовала в month-12/step-1

2022-11-10 15:52 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец!**

- Практические все замечания с прошлого ревью были исправлены.

### **Но всё ещё есть несколько замечаний, которые нужно исправить:**

- "Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. Отметил в коде.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. `components\ui\column\column.tsx`.

- Очередь:

  - Если попытаться добавить элемент после того как очередь заполнена, пропадает надпись tail.
    https://disk.yandex.ru/d/BS6BuvA6Yst44A

  - По чек-листу во время анимации алгоритмов на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма;

- Связный список:

  - По чек-листу во время анимации алгоритмов на активной кнопке отображается прелоадер, остальные кнопки и поля ввода неактивны (состояние disabled) до завершения работы алгоритма;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-10 15:52 UTC, ArslanDev666 commented on src/utils/functions.ts
> +};
**Надо исправить:** 
По чек-листу.
функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

Т.е эта функция должна лежать в папке `fibonacci-page` и файле `utils.ts`, рядом со страницей.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/utils/functions.ts
> +  };
**Надо исправить:** 
По чек-листу.
функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

Т.е эта функция должна лежать в папке `string` и файле `utils.ts`, рядом со страницей.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/utils/functions.ts
> +};
**Надо исправить:** 
По чек-листу.
функции, которые реализуют работу алгоритмов и не взаимодействуют с компонентом, вынесены в отдельные файлы utils.ts в папке соответствующего компонента;

Т.е эта функция должна лежать в папке `sorting-page` и файле `utils.ts`, рядом со страницей.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +            maxLength={4}
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    if (list.getSize() >= 9) {
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +    list.getSize() >= 10 || !inputValue
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +        Array.from({ length: 4 }, () => getRandomNumber(0, 99).toString())
**Надо исправить:**

`4`

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +  const defaultQueue = Array.from({ length: 7 }, () => ({
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +  const [queue, setQueue] = useState(new Queue<TQueueItem>(7));
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    if (queue.getHead() === 7 && queue.getTail() === 7 && queue.isEmpty()) {
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +          {arr && arr.slice(0, 7).map((item, index) =>
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +          maxLength={4}
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-10 15:52 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +          maxLength={4}
**Надо исправить:**

"Магические" значения (Различные ограничения, тайминги, и т.п.) лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-11-11 15:41 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Работа отклонена от проверки, проект не запускается.

- https://yadi.sk/d/uU_o8ku82ctACA

Также удалите из репозитория папку node_modules. Вот примерный гайд, как это можно сделать (А лучше всего обратитесь к наставнику за помощью): https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode

2022-11-12 05:27 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены.

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении!**

### **Сделает код лучше:**

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили. `components\ui\column\column.tsx`.

- У вас дублируются некоторые константы, в файлах `src/constants/delays.ts` и `utils/constants.ts`, лучше избегать дублирования кода.

2022-11-20 23:48 UTC, merged